# -*- coding: utf-8 -*-
# Copyright 2022 Mon Logistics Group <https://www.mlholding.mn>
# Created by Umbaa. 2022-12-02

from . import crm_lead
from . import inquiry_send_mail_to_agents
from . import worldwide_freights
from . import worldwide_user_groups
from . import worldwide_confirm_quotation_email
from . import sale_order_line
from . import sale_order
from . import res_partner
from . import res_company
from . import res_currency
from . import arrival_notice
from . import account_incoterms
# from . import freight_container_details
from . import freights_shipments_delay
from . import hr_employee
from . import worldwide_freight_photo
from . import worldwide_confirm_agent_quotation
from . import freights_location
from . import service_types
from . import confirm_agent_quotation
from . import freights_service
from . import quotation_confirm_wizard
from . import freight_stations
from . import freights_search_wizard
from . import freights_type
from . import freights_terms
from . import freights_points
from . import freights_terminal
from . import freights_hscode_category
from . import freights_tara
from . import preview_pdf_wizard
from . import add_employee
from . import cargo_receipt_data
from . import quotation_agents_mails
from . import freights_route_category
from . import freights_wagon_type
from . import freights_truck_type
from . import freights_quotation
from . import freights_agent_inquiry
from . import Freights_agent_costs
from . import freights_employee_role
from . import worldwide_quotation_data
from . import worldwide_quotation_mail_data
from . import worldwide_cron_jobs
from . import freights_route
from . import freights_confirm_quotation_header
from . import freights_container_movement
from . import freights_shipping_line
from . import inquiry_mail_to
from . import inquiry_data
from . import worldwide_transport_type
from . import base_condition
from . import freights_container_type
from . import freights_containers
from . import freights_order_routes
from . import freights_route_shipment
from . import freights_shipment_type
from . import freights_shipments
from . import freights_packages
from . import freights_payment_service 
from . import freights_release_status
from . import freights_abilities
from . import freights_agent_review
from . import freights_client_feedback
from . import freight_incexc_service
from . import currency_line
from . import freights_service_type
from . import worldwide_reason_remark
from . import worldwide_reason
from . import freights_cost_type
from . import delivery_rate
from . import worldwide_invoice_data
from . import package_request
from . import route_data
from . import freight_transient
from . import freights_insurance
from . import monthly_report
from . import monthly_report_data
from . import fob_rates
from . import delivery_rates
from . import demurrages
from . import thc_rate
from . import socprice_rates
from . import customer_rates
from . import shipment_order_data
from . import packages_wizard
from . import freights_container_movement
from . import container_yard_data
from . import insurance_cost
from . import freights_shipments_remark
from . import freight_demmurage