from . import res_company
from . import trucking_add_field
from . import trucking_base
from . import trucking_freight_photo
from . import trucking_type
from . import trucking_incoterms
from . import trucking_shipment
from . import trucking_address
from . import trucking_port
from . import trucking_currency
from . import trucking_services
from . import trucking_points
from . import trucking_route
from . import trucking_quotation_data
from . import invoice_data
from . import trucking_orders
from . import trucking_package
from . import trucking_mail_data
from . import trucking_package_data
from . import trucking_transport_mail_data
from . import trucking_location
from . import trucking_document_data
from . import mail_counter
from . import trucking_expenditure_data
from . import service_wizard
from . import fleet_vehicle
from . import sale_order_line
from . import sale_order
from . import trucking_budget_data
from . import sale_order_quotation
from . import trucking_core
from . import trucking_include_exclude